/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models

import clients.cartapi.models.ArticleDto
import clients.cartapi.models.ChosenExtrasDto

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param article 
 * @param chosenExtras 
 */

data class ArticleConfigurationDto (
    @JsonProperty("Article")
    val article: ArticleDto? = null,
    @JsonProperty("ChosenExtras")
    val chosenExtras: ChosenExtrasDto? = null
)

