/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param cartId 
 * @param vendorId 
 * @param channel 
 * @param accountId 
 * @param publicCartId 
 * @param lastUpdateDate 
 * @param products 
 */

data class CartInfo (
    @JsonProperty("CartId")
    val cartId: kotlin.Int? = null,
    @JsonProperty("VendorId")
    val vendorId: kotlin.Int? = null,
    @JsonProperty("Channel")
    val channel: kotlin.String? = null,
    @JsonProperty("AccountId")
    val accountId: kotlin.String? = null,
    @JsonProperty("PublicCartId")
    val publicCartId: java.util.UUID? = null,
    @JsonProperty("LastUpdateDate")
    val lastUpdateDate: java.time.OffsetDateTime? = null,
    @JsonProperty("Products")
    val products: kotlin.Int? = null
)

