/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models

import clients.cartapi.models.FloatingFrameOptionDto

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param option 
 */

data class ChosenFloatingFrameDto (
    @JsonProperty("Option")
    val option: FloatingFrameOptionDto? = null
)

