/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param fromDate 
 * @param toDate 
 */

data class ForgottenCartsRequestModel (
    @JsonProperty("FromDate")
    val fromDate: java.time.OffsetDateTime,
    @JsonProperty("ToDate")
    val toDate: java.time.OffsetDateTime
)

