/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param rel 
 * @param href 
 * @param type 
 */

data class Link (
    @JsonProperty("Rel")
    val rel: kotlin.String? = null,
    @JsonProperty("Href")
    val href: kotlin.String? = null,
    @JsonProperty("Type")
    val type: kotlin.String? = null
)

