/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param channel 
 * @param locale 
 * @param accountId 
 */

data class NewShoppingCart (
    @JsonProperty("Channel")
    val channel: kotlin.String? = null,
    @JsonProperty("Locale")
    val locale: kotlin.String? = null,
    @JsonProperty("AccountId")
    val accountId: kotlin.String? = null
)

