/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models

import clients.cartapi.models.ArticleConfigurationDto
import clients.cartapi.models.Image
import clients.cartapi.models.Link
import clients.cartapi.models.Template

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param ID 
 * @param productID 
 * @param timestampCreated 
 * @param discountable 
 * @param links 
 * @param version 
 * @param cartID 
 * @param channelName 
 * @param locale 
 * @param amount 
 * @param configuration 
 * @param storedProductID 
 * @param uploadID 
 * @param template 
 * @param previewImageID 
 * @param images 
 * @param discountCode 
 * @param editorID 
 * @param editorTypeID 
 * @param computerName 
 * @param productTitle 
 * @param productFileLocation 
 * @param productContentSpineWidth 
 */

data class ShoppingCartItem (
    @JsonProperty("ID")
    val ID: kotlin.String? = null,
    @JsonProperty("ProductID")
    val productID: java.util.UUID? = null,
    @JsonProperty("TimestampCreated")
    val timestampCreated: java.time.OffsetDateTime? = null,
    @JsonProperty("Discountable")
    val discountable: kotlin.Boolean? = null,
    @JsonProperty("Links")
    val links: kotlin.Array<Link>? = null,
    @JsonProperty("Version")
    val version: kotlin.String? = null,
    @JsonProperty("CartID")
    val cartID: java.util.UUID? = null,
    @JsonProperty("ChannelName")
    val channelName: kotlin.String? = null,
    @JsonProperty("Locale")
    val locale: kotlin.String? = null,
    @JsonProperty("Amount")
    val amount: kotlin.Int? = null,
    @JsonProperty("Configuration")
    val configuration: ArticleConfigurationDto? = null,
    @JsonProperty("StoredProductID")
    val storedProductID: kotlin.Int? = null,
    @JsonProperty("UploadID")
    val uploadID: kotlin.String? = null,
    @JsonProperty("Template")
    val template: Template? = null,
    @JsonProperty("PreviewImageID")
    val previewImageID: kotlin.String? = null,
    @JsonProperty("Images")
    val images: kotlin.Array<Image>? = null,
    @JsonProperty("DiscountCode")
    val discountCode: kotlin.String? = null,
    @JsonProperty("EditorID")
    val editorID: kotlin.String? = null,
    @JsonProperty("EditorTypeID")
    val editorTypeID: kotlin.String? = null,
    @JsonProperty("ComputerName")
    val computerName: kotlin.String? = null,
    @JsonProperty("ProductTitle")
    val productTitle: kotlin.String? = null,
    @JsonProperty("ProductFileLocation")
    val productFileLocation: kotlin.String? = null,
    @JsonProperty("ProductContentSpineWidth")
    val productContentSpineWidth: kotlin.Double? = null
)

