/**
* CartApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: api
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package clients.cartapi.models

import clients.cartapi.models.Link
import clients.cartapi.models.ShoppingCartItem

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param ID 
 * @param cartItems 
 * @param links 
 * @param discountCodes 
 * @param coupon 
 * @param channel 
 * @param locale 
 * @param accountId 
 */

data class ShoppingCart (
    @JsonProperty("ID")
    val ID: kotlin.String? = null,
    @JsonProperty("CartItems")
    val cartItems: kotlin.Array<ShoppingCartItem>? = null,
    @JsonProperty("Links")
    val links: kotlin.Array<Link>? = null,
    @JsonProperty("DiscountCodes")
    val discountCodes: kotlin.Array<kotlin.String>? = null,
    @JsonProperty("Coupon")
    val coupon: kotlin.String? = null,
    @JsonProperty("Channel")
    val channel: kotlin.String? = null,
    @JsonProperty("Locale")
    val locale: kotlin.String? = null,
    @JsonProperty("AccountId")
    val accountId: kotlin.String? = null
)

